name: py-in-context-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda>=11.8
  - pytorch::torchtext>=0.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - transformers
    - sentence-transformers
    - tensorboard
    - mamba-ssm==2.2.4